feat: auction view for NFT packs
metaplex-foundation/metaplex pull request #1160
Opened 2021-12-08 15:32 UTC by ViacheslavMylostyvyi

Task: https://app.asana.com/0/1201360309822272/1201458016134730
Description: Same view for NFT packs and regular NFTs while creating an auctio
<img width="1090" alt="Знімок екрана  о 16 44 10" src="https://user-images.githubusercontent.com/20477424/145236174-3e6208ed-c542-41ca-a1ef-5777f6907213.png">
n

2021-12-09 08:34 UTC, zaxozhu requested changes

2021-12-09 08:34 UTC, zaxozhu commented on js/packages/web/src/components/PackCard/index.tsx
> +            close && close();
```suggestion
            close();
```

2021-12-09 08:34 UTC, zaxozhu commented on js/packages/web/src/components/PackCard/index.tsx
> +  close?: () => void;
```suggestion
  onClose?: () => void;
```

2021-12-09 08:34 UTC, zaxozhu commented on js/packages/web/src/views/auctionCreate/AuctionItemCard.tsx
> +  const voucher = Object.values(vouchers).find(v => v?.info?.master === masterEdition);
Let's hide it under the env variable and please test it by removing ENABLE_NFT_PACKS from .env

```ts
const shouldShowPacks = process.env.NEXT_ENABLE_NFT_PACKS === 'true';
if (shouldShowPacks) {
  const voucher = Object.values(vouchers).find(v => v?.info?.master === masterEdition);
  if (voucher) { 
     ... 
  }
}
```

2021-12-09 08:34 UTC, zaxozhu commented on js/packages/web/src/views/auctionCreate/artSelector.tsx
> +import AuctionItemCard from "./AuctionItemCard";
```suggestion
import AuctionItemCard from './AuctionItemCard';
```

2021-12-09 08:34 UTC, zaxozhu commented on js/packages/web/src/views/auctionCreate/AuctionItemCard.tsx
> +          close={onClose}
```suggestion
          onClose={onClose}
```

2021-12-09 08:51 UTC, kurpav commented on js/packages/web/src/views/auctionCreate/AuctionItemCard.tsx
> +import PackCard from "../../components/PackCard";
please fix quotes

2021-12-09 14:09 UTC, zaxozhu commented on js/packages/web/src/views/auctionCreate/AuctionItemCard.tsx
> +  if (shouldShowPacks) {
```suggestion
  if (!shouldShowPacks) {
    return (
    <ArtCard
      pubkey={current.metadata.pubkey}
      preview={false}
      onClick={onSelect}
      className={isSelected ? 'selected-card art-card-for-selector' : 'not-selected-card art-card-for-selector'}
      onClose={onClose}
    />
  );
  }
```

2021-12-09 14:09 UTC, zaxozhu commented on js/packages/web/src/views/auctionCreate/AuctionItemCard.tsx
> +  if (shouldShowPacks) {
Let's have the shortest block first

2021-12-10 09:16 UTC, zaxozhu approved these changes

2021-12-10 09:40 UTC, kurpav approved these changes

2021-12-10 13:18 UTC, merged