Allow to upload files with unlimited size through the user's Arweave wallet
metaplex-foundation/metaplex pull request #801
Opened 2021-10-25 22:41 UTC by JuanRdBO

![Screenshot from 2021-10-26 00-41-21](https://user-images.githubusercontent.com/28183468/138780684-0e7d68a7-70a9-43a1-b9c1-3beed4267db2.png)

2021-10-29 22:04 UTC, JuanRdBO commented
Hey @bhgames I'd appreciate a review of this! :-)

2021-11-06 10:54 UTC, bhgames requested changes

2021-11-06 10:54 UTC, bhgames commented on js/packages/web/src/actions/nft.tsx
> +    if (fileType == "image/jpeg") {
Check image/gif too, these also work

2021-11-06 10:54 UTC, bhgames commented on js/packages/web/src/actions/nft.tsx
> +  console.log("ARWEAVEDATA", data)
r3emove

2021-11-06 10:54 UTC, bhgames commented on js/packages/web/src/actions/nft.tsx
> +  const filesLessThan10mb = files.filter((m) => m.size < 10_000_000);
9mb is safer limit

2021-11-06 10:54 UTC, bhgames commented on js/packages/web/src/actions/nft.tsx
> +    console.log("PREUPLOAD AR", data, txid, env)
remove

2021-11-06 10:54 UTC, bhgames commented on js/packages/web/src/actions/nft.tsx
> +    progressCallback(6);
same callback again - 6

2021-11-19 02:06 UTC, bhgames commented
Closing due to inactivity

2021-11-19 02:06 UTC, closed without merging